namespace Conductor.Core.Tests.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using Conductor.Core.Models;
    using FluentAssertions;
    using Xunit;

    /// <summary>
    /// Unit tests for Credential model.
    /// </summary>
    public class CredentialTests
    {
        #region TenantId-Tests

        [Fact]
        public void TenantId_WhenNull_ThrowsArgumentNullException()
        {
            Credential cred = new Credential();
            Action act = () => cred.TenantId = null;
            act.Should().Throw<ArgumentNullException>().WithParameterName("TenantId");
        }

        [Fact]
        public void TenantId_WhenEmpty_ThrowsArgumentNullException()
        {
            Credential cred = new Credential();
            Action act = () => cred.TenantId = "";
            act.Should().Throw<ArgumentNullException>().WithParameterName("TenantId");
        }

        #endregion

        #region UserId-Tests

        [Fact]
        public void UserId_WhenNull_ThrowsArgumentNullException()
        {
            Credential cred = new Credential();
            Action act = () => cred.UserId = null;
            act.Should().Throw<ArgumentNullException>().WithParameterName("UserId");
        }

        [Fact]
        public void UserId_WhenEmpty_ThrowsArgumentNullException()
        {
            Credential cred = new Credential();
            Action act = () => cred.UserId = "";
            act.Should().Throw<ArgumentNullException>().WithParameterName("UserId");
        }

        #endregion

        #region BearerToken-Tests

        [Fact]
        public void BearerToken_WhenNullOrEmpty_AutoGenerates()
        {
            Credential cred = new Credential();
            cred.BearerToken.Should().NotBeNullOrEmpty();
        }

        [Fact]
        public void BearerToken_WhenProvided_UsesProvidedValue()
        {
            Credential cred = new Credential();
            cred.BearerToken = "custom_token_12345";
            cred.BearerToken.Should().Be("custom_token_12345");
        }

        [Fact]
        public void BearerToken_AutoGenerated_Is64Characters()
        {
            Credential cred = new Credential();
            cred.BearerToken.Should().HaveLength(64);
        }

        [Fact]
        public void BearerToken_MultipleInstances_AreUnique()
        {
            Credential cred1 = new Credential();
            Credential cred2 = new Credential();
            cred1.BearerToken.Should().NotBe(cred2.BearerToken);
        }

        #endregion

        #region Default-Value-Tests

        [Fact]
        public void Active_DefaultsToTrue()
        {
            Credential cred = new Credential();
            cred.Active.Should().BeTrue();
        }

        [Fact]
        public void Name_DefaultsToNull()
        {
            Credential cred = new Credential();
            cred.Name.Should().BeNull();
        }

        [Fact]
        public void Labels_InitializesAsEmptyList()
        {
            Credential cred = new Credential();
            cred.Labels.Should().NotBeNull();
            cred.Labels.Should().BeEmpty();
        }

        [Fact]
        public void Tags_InitializesAsEmptyDictionary()
        {
            Credential cred = new Credential();
            cred.Tags.Should().NotBeNull();
            cred.Tags.Should().BeEmpty();
        }

        #endregion

        #region FromDataRow-Tests

        [Fact]
        public void FromDataRow_WithNullRow_ReturnsNull()
        {
            Credential result = Credential.FromDataRow(null);
            result.Should().BeNull();
        }

        [Fact]
        public void FromDataRow_WithValidData_CreatesInstance()
        {
            DataTable table = CreateTestDataTable();
            DataRow row = table.NewRow();
            row["id"] = "cred_test123";
            row["tenantid"] = "ten_test";
            row["userid"] = "usr_test";
            row["name"] = "API Key 1";
            row["bearertoken"] = "test_bearer_token_1234567890abcdef";
            row["active"] = true;
            row["createdutc"] = DateTime.UtcNow;
            row["lastupdateutc"] = DateTime.UtcNow;
            table.Rows.Add(row);

            Credential cred = Credential.FromDataRow(row);

            cred.Should().NotBeNull();
            cred.Id.Should().Be("cred_test123");
            cred.TenantId.Should().Be("ten_test");
            cred.UserId.Should().Be("usr_test");
            cred.Name.Should().Be("API Key 1");
            cred.BearerToken.Should().Be("test_bearer_token_1234567890abcdef");
        }

        #endregion

        #region FromDataTable-Tests

        [Fact]
        public void FromDataTable_WithNullTable_ReturnsNull()
        {
            List<Credential> result = Credential.FromDataTable(null);
            result.Should().BeNull();
        }

        [Fact]
        public void FromDataTable_WithEmptyTable_ReturnsEmptyList()
        {
            DataTable table = CreateTestDataTable();
            List<Credential> result = Credential.FromDataTable(table);
            result.Should().NotBeNull();
            result.Should().BeEmpty();
        }

        [Fact]
        public void FromDataTable_WithMultipleRows_ReturnsCollection()
        {
            DataTable table = CreateTestDataTable();
            for (int i = 0; i < 3; i++)
            {
                DataRow row = table.NewRow();
                row["id"] = $"cred_test{i}";
                row["tenantid"] = "ten_test";
                row["userid"] = "usr_test";
                row["bearertoken"] = $"token_{i}";
                row["active"] = true;
                table.Rows.Add(row);
            }

            List<Credential> result = Credential.FromDataTable(table);
            result.Should().HaveCount(3);
        }

        #endregion

        #region Id-Tests

        [Fact]
        public void Id_StartsWithCorrectPrefix()
        {
            Credential cred = new Credential();
            cred.Id.Should().StartWith("cred_");
        }

        #endregion

        #region Helper-Methods

        private DataTable CreateTestDataTable()
        {
            DataTable table = new DataTable();
            table.Columns.Add("id", typeof(string));
            table.Columns.Add("tenantid", typeof(string));
            table.Columns.Add("userid", typeof(string));
            table.Columns.Add("name", typeof(string));
            table.Columns.Add("bearertoken", typeof(string));
            table.Columns.Add("active", typeof(bool));
            table.Columns.Add("createdutc", typeof(DateTime));
            table.Columns.Add("lastupdateutc", typeof(DateTime));
            table.Columns.Add("labels", typeof(string));
            table.Columns.Add("tags", typeof(string));
            table.Columns.Add("metadata", typeof(string));
            return table;
        }

        #endregion
    }
}
